site_name: Work Setup
site_url: https://buerostuff.github.io/work-setup

extra:
  generator: false
  homepage: /work-setup/

theme:
  name: material
  icon:
    logo: material/console
  font:
    text: Fira Sans
    code: Fira Code
  palette:
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Dark mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - Home: index.md
  - Software: software.md
  - Git SSH Setup: git-ssh-setup.md
  - Git Commands: git-commands.md
  - Docker: docker-setup.md
  - Azure CLI: azure-cli.md
  - Terminal: terminal-setup.md
  - Fonts: fonts.md
